image: debian:stretch
stages:
  - build

default:
  tags:
    - shared
  before_script:
    - echo "# Before script"

build_and_publish_qualif_app:
  stage: build
  variables:
    LATEST_VERSION: qualif
  rules:
    - if: ($CI_COMMIT_BRANCH =~ /^qualif\/*/ )
  script:
    - echo "# Build $LATEST_VERSION"
    - env
    - ci/version.sh

build_and_publish_latest_app:
  stage: build
  variables:
    LATEST_VERSION: latest
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^v*/ && $CI_COMMIT_BRANCH == null
    - if: $CI_COMMIT_BRANCH =~ /^develop/
  script:
    - echo "# Build $LATEST_VERSION"
    - env
    - ci/version.sh
