image: debian:stretch
stages:
  - build

default:
  tags:
    - shared
  before_script:
    - echo "# Before script"

build_and_publish_qualif_app:
  stage: build
  variables:
    LATEST_VERSION: qualif
  rules:
    - if: ($CI_COMMIT_BRANCH =~ /^qualif\/*/ )
  script:
    - echo "# Build $LATEST_VERSION"

build_and_publish_latest_app:
  stage: build
  variables:
    LATEST_VERSION: latest
  rules:
    - if: ($CI_COMMIT_BRANCH =~ /^develop/  && $CI_COMMIT_TAG =~ /^[v].*/)
  script:
    - echo "# Build $LATEST_VERSION"
