dist: trusty
sudo: required

language: minimal

services:
  - docker

branches:
  except:
    - /^pr\..*/

env:
  - DOCKER_COMPOSE_VERSION=1.19.0

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo rm -rf /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/
  - sudo apt-get -q update
  - sudo apt-get install -qy make apt-transport-https ca-certificates curl software-properties-common gawk jq parallel
  - sudo pip install bashate
  - sudo apt-get install shellcheck

before_script:
  - uname -a
  - type -a docker-compose && docker-compose version
  - docker version

script:
  - shellcheck test.sh
  - bashate -i E006 test.sh
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash deploy.sh staging $TRAVIS_BRANCH
    skip_cleanup: true
after_script:
  - echo "END"
