sudo: required

langage: minimal

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt-get -q update
  - sudo apt-get install -qy apt-transport-https ca-certificates curl software-properties-common gawk jq parallel

before_script:
  - uname -a
  - type -a docker-compose && docker-compose version
  - docker version

