# This is a basic workflow to help you get started with Actions

name: CI release

on:
  release:
    types: [published]
#on:
#  push:
#    tags:
#      - "v*"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag
      - name: Extract version
        shell: bash
        run: echo "##[set-output name=version;]$(git describe --tags --always)"
        id: code_version

      - name: job release
        run: |
          echo "publish RELEASE version latest ${{ steps.code_version.outputs.version }} ${{ steps.extract_tag.outputs.version }}"

      - name: deploy on github branch releases
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: success()
        env:
          PUBLISH_BRANCH: releases
          PUBLISH_DIR: ./

