# This is a basic workflow to help you get started with Actions

name: CI release

on:
  release:
    types: [published]
#on:
#  push:
#    tags:
#      - "v*"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prepare tag
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"

      - name: job release
        run: |
          cat <<'EOF'
          publish RELEASE
          version latest
          tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          tag_message: Release ${{ steps.prepare_tag.outputs.tag_name }}
          EOF
