on:
  workflow_dispatch:
    inputs:
      terraform_taint_list:
        description: 'space separated list of terraform ressource to taint, exemple: module.a[0] module.b[0]'
        required: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check for changes
        run: |
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "taint: ${{ inputs.terraform_taint_list}}"
          [[ -z "${{ inputs.terraform_taint_list}}" ]] && exit 0
          list=(${{ inputs.terraform_taint_list}}) ; for taint in "${list[@]}" ; do  echo "-> ${taint}"; done


